### PR TITLE
Release 2.0.0

### LINKED ISSUE #46: GAMES_000I Sprint 4 finish
TODO:
- [x] testing
- [x] create screenshots
- [x] write report 
- [x] perform release
- [x] set tag
- [x] release

### PR DESCRIPTION
**Pull request by Karatekuh**
## Checklist for Pull Request
 - [x]  Acceptance criteria, read the issue so that you know what should be done in this PR. Only check if you are sure everything is implemented.
 - [x]  Unit tests, there are enough of them.
 - [x]  UI tests are there if applicable
 - [x] Changes tested on emulator or real device

closes #46

### CODE REVIEW

**Review by dermyGIT — APPROVED** [review]
looks fine

**Review by glocka — APPROVED** [review]

**Review by brovic09 — APPROVED** [review]
:tada:

**Comment by steni510** [comment]
Looks fine for me

**Review by steni510 — APPROVED** [review]
Looks good

**Review by glocka — APPROVED** [review]

**Review by Sam-13 — APPROVED** [review]
looks fantastic ;)

**Review by brovic09 — APPROVED** [review]
:tada:

**Comment by glocka** [comment]
it is sooooooooooooooooooooooo awsome

**Review by pkohout — APPROVED** [review]

**Review by schanes13 — APPROVED** [review]

**Review by pkohout — APPROVED** [review]

**Pull request merged**
